name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install pytest pytest-cov
          fi

      - name: Run tests with coverage (XML + terminal)
        run: |
          python -m pytest --cov=app --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          verbose: true
        env:
          # If your repo is PRIVATE or tokenless upload fails, set this secret in GitHub:
          # Settings > Secrets and variables > Actions > New repository secret
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
